name: format-pr
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Since EnergyModelsBase doesn't have binary dependencies,
        # only test on a subset of possible platforms.
        include:
          - version: '1'  # The latest point-release (Linux)
            os: ubuntu-latest
            arch: x64
          - version: '1'  # The latest point-release (Windows)
            os: windows-latest
            arch: x64
          - version: 'lts'  # lts 
            os: ubuntu-latest
            arch: x64
          - version: 'lts'  # lts
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter and format
        run: |
          julia  -e 'import Pkg; Pkg.add("JuliaFormatter")'
          julia  -e 'using JuliaFormatter; format(".")'

      # https://github.com/marketplace/actions/create-pull-request
      # https://github.com/peter-evans/create-pull-request#reference-example
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format .jl files
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"